this.PATHS = [
    // -system-
    {"type": "js", "url": "invoices/lib/json2.js", "buildTo": "invoices/build/helper.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.js", "buildTo": "invoices/build/jquery.js"},
    {"type": "js", "url": "invoices/lib/jquery.iframe-transport.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/underscore.js", "buildTo": "invoices/build/underscore.js"},
    {"type": "js", "url": "invoices/lib/backbone.js", "buildTo": "invoices/build/backbone.js"},
    {"type": "js", "url": "invoices/lib/backbone.l10n.js", "buildTo": "invoices/build/backbone.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/backbone.collection.search.js", "buildTo": "invoices/build/backbone.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/backbone.collection.unique.js", "buildTo": "invoices/build/backbone.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/backbone.model.toJSONExt.js", "buildTo": "invoices/build/backbone.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/backbone.collection.toJSONExt.js", "buildTo": "invoices/build/backbone.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.ui.min.js", "buildTo": "invoices/build/jquery.ui.min.js"},
    {"type": "js", "url": "invoices/lib/jquery.iautocomplete.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.iplaceholder.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.ierror.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.ierrorDialog.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/jquery.itabs.js", "buildTo": "invoices/build/jquery.plugins.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/date.js", "buildTo": "invoices/build/helper.js", "build": "jsc"},
    {"type": "js", "url": "invoices/lib/sprintf.js", "buildTo": "invoices/build/helper.js", "build": "jsc"},
    
    // -globalmenu-
	{"type": "ajax", "url": "invoices/app/globalmenu/template.globalMenu.tpl", "name": "globalmenu.globalMenu", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "js", "url": "invoices/app/globalmenu/model.globalMenuItem.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/globalmenu/collection.globalMenu.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/globalmenu/view.globalMenu.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	
	// -buyersGroups-
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroups.tpl", "name": "buyersGroups.buyersGroups", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsItem.tpl", "name": "buyersGroups.buyersGroupsItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsItemEdit.tpl", "name": "buyersGroups.buyersGroupsItemEdit", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsAdd.tpl", "name": "buyersGroups.buyersGroupsAdd", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsDel.tpl", "name": "buyersGroups.buyersGroupsDel", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsLoader.tpl", "name": "buyersGroups.buyersGroupsLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersGroupsLoaderDialog.tpl", "name": "buyersGroups.buyersGroupsLoaderDialog", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/template.buyersDialogImport.tpl", "name": "buyersGroups.buyersDialogImport", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyersGroups/l10n.ru.json", "name": "buyersGroups.ru", "buildTo": "invoices/build/l10n.ru.js", "build": "l10n"},
	{"type": "js", "url": "invoices/app/buyersGroups/model.buyersGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/buyersGroups/collection.buyersGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/buyersGroups/view.buyersGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	
	// -buyers-
	{"type": "ajax", "url": "invoices/app/buyers/template.buyers.tpl", "name": "buyers.buyers", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyers/template.buyersItem.tpl", "name": "buyers.buyersItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyers/template.buyersItemEdit.tpl", "name": "buyers.buyersItemEdit", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyers/template.buyersItemNew.tpl", "name": "buyers.buyersItemNew", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyers/template.buyersDel.tpl", "name": "buyers.buyersDel", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "ajax", "url": "invoices/app/buyers/template.buyersLoader.tpl", "name": "buyers.buyersLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
	{"type": "js", "url": "invoices/app/buyers/model.buyers.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/buyers/collection.buyers.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	{"type": "js", "url": "invoices/app/buyers/view.buyers.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
	
	// -goodsGroups-
	{"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroups.tpl", "name": "goodsGroups.goodsGroups", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsItem.tpl", "name": "goodsGroups.goodsGroupsItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsItemEdit.tpl", "name": "goodsGroups.goodsGroupsItemEdit", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsAdd.tpl", "name": "goodsGroups.goodsGroupsAdd", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsDel.tpl", "name": "goodsGroups.goodsGroupsDel", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsLoader.tpl", "name": "goodsGroups.goodsGroupsLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/template.goodsGroupsLoaderDialog.tpl", "name": "goodsGroups.goodsGroupsLoaderDialog", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goodsGroups/l10n.ru.json", "name": "goodsGroups.ru", "buildTo": "invoices/build/l10n.ru.js", "build": "l10n"},
    {"type": "js", "url": "invoices/app/goodsGroups/model.goodsGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/goodsGroups/collection.goodsGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/goodsGroups/view.goodsGroups.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -goods-
    {"type": "ajax", "url": "invoices/app/goods/template.goods.tpl", "name": "goods.goods", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goods/template.goodsItem.tpl", "name": "goods.goodsItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goods/template.goodsItemEdit.tpl", "name": "goods.goodsItemEdit", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goods/template.goodsItemNew.tpl", "name": "goods.goodsItemNew", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goods/template.goodsDel.tpl", "name": "goods.goodsDel", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/goods/template.goodsLoader.tpl", "name": "goods.goodsLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "js", "url": "invoices/app/goods/model.goods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/goods/collection.goods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/goods/view.goods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -invoicesStatus-
    {"type": "ajax", "url": "invoices/app/invoicesStatus/template.invoicesStatus.tpl", "name": "invoicesStatus.invoicesStatus", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "js", "url": "invoices/app/invoicesStatus/model.invoicesStatus.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoicesStatus/collection.invoicesStatus.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoicesStatus/view.invoicesStatus.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -invoices-
    {"type": "ajax", "url": "invoices/app/invoices/template.invoices.tpl", "name": "invoices.invoices", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/invoices/template.invoicesItem.tpl", "name": "invoices.invoicesItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/invoices/template.invoicesLoader.tpl", "name": "invoices.invoicesLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "js", "url": "invoices/app/invoices/model.invoices.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoices/collection.invoices.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoices/view.invoices.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -invoice-
    {"type": "ajax", "url": "invoices/app/invoice/template.invoice.tpl", "name": "invoice.invoice", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/invoice/template.invoiceLoader.tpl", "name": "invoice.invoiceLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "js", "url": "invoices/app/invoice/model.invoiceBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/collection.invoiceBuyers.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/model.invoiceGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/collection.invoiceGoodss.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/model.invoice.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/collection.invoice.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/invoice/view.invoice.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -itemInvoice-
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEdit.tpl", "name": "itemInvoice.itemInvoiceEdit", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceView.tpl", "name": "itemInvoice.itemInvoiceView", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceSend.tpl", "name": "itemInvoice.itemInvoiceSend", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditGoodsItem.tpl", "name": "itemInvoice.itemInvoiceEditGoodsItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditBuyerItem.tpl", "name": "itemInvoice.itemInvoiceEditBuyerItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditGoodsNew.tpl", "name": "itemInvoice.itemInvoiceEditGoodsNew", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditBuyerHelpGroup.tpl", "name": "itemInvoice.itemInvoiceEditBuyerHelpGroup", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditBuyerHelpItem.tpl", "name": "itemInvoice.itemInvoiceEditBuyerHelpItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditGoodsHelpGroup.tpl", "name": "itemInvoice.itemInvoiceEditGoodsHelpGroup", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditGoodsHelpItem.tpl", "name": "itemInvoice.itemInvoiceEditGoodsHelpItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditNewGoodsItem.tpl", "name": "itemInvoice.itemInvoiceEditNewGoodsItem", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditDialog.tpl", "name": "itemInvoice.itemInvoiceEditDialog", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditDialogLoader.tpl", "name": "itemInvoice.itemInvoiceEditDialogLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditLoaderGoodsGroup.tpl", "name": "itemInvoice.itemInvoiceEditLoaderGoodsGroup", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditLoaderBuyersGroup.tpl", "name": "itemInvoice.itemInvoiceEditLoaderBuyersGroup", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditLoaderAtcmplt.tpl", "name": "itemInvoice.itemInvoiceEditLoaderAtcmplt", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceEditAtcmpltEmpty.tpl", "name": "itemInvoice.itemInvoiceEditAtcmpltEmpty", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceViewBuyers.tpl", "name": "itemInvoice.itemInvoiceViewBuyers", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceViewLoader.tpl", "name": "itemInvoice.itemInvoiceViewLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceViewDialog.tpl", "name": "itemInvoice.itemInvoiceViewDialog", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceSendLoader.tpl", "name": "itemInvoice.itemInvoiceSendLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceSendSuccess.tpl", "name": "itemInvoice.itemInvoiceSendSuccess", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoiceSendError.tpl", "name": "itemInvoice.itemInvoiceSendError", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoicePrint.tpl", "name": "itemInvoice.itemInvoicePrint", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoicePrintLoader.tpl", "name": "itemInvoice.itemInvoicePrintLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/itemInvoice/template.itemInvoicePrintInvoice.tpl", "name": "itemInvoice.itemInvoicePrintInvoice", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    
    {"type": "js", "url": "invoices/app/itemInvoice/view.itemInvoiceEdit.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoice/view.itemInvoiceView.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoice/view.itemInvoiceSend.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoice/view.itemInvoicePrint.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -itemInvoiceBuyerHelp-
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/model.itemInvoiceHelpItem.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/collection.itemInvoiceHelpItem.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/model.itemInvoiceHelpGroupBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/collection.itemInvoiceHelpGroupBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/model.itemInvoiceHelpGroupGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/collection.itemInvoiceHelpGroupGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/model.itemInvoiceHelpSelectionGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/collection.itemInvoiceHelpSelectionGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/model.itemInvoiceHelpSelectionBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/collection.itemInvoiceHelpSelectionBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/view.itemInvoiceHelpBuyer.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/itemInvoiceHelp/view.itemInvoiceHelpGoods.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    // -merchant-
    {"type": "ajax", "url": "invoices/app/merchant/template.merchant.tpl", "name": "merchant.merchant", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/merchant/template.merchantLoader.tpl", "name": "merchant.merchantLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/merchant/template.merchantSaveLoader.tpl", "name": "merchant.merchantSaveLoader", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/merchant/template.merchantDialogLogo.tpl", "name": "merchant.merchantDialogLogo", "buildTo": "invoices/build/tmp.js", "build": "tmp"},
    {"type": "ajax", "url": "invoices/app/merchant/l10n.ru.json", "name": "merchant.ru", "buildTo": "invoices/build/l10n.ru.js", "build": "l10n"},
    {"type": "ajax", "url": "invoices/app/merchant/l10n.ua.json", "name": "merchant.ua", "buildTo": "invoices/build/l10n.ua.js", "build": "l10n"},
    {"type": "js", "url": "invoices/app/merchant/model.merchant.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/merchant/view.merchant.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    
    {"type": "js", "url": "invoices/app/model.router.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/collection.routers.js", "buildTo": "invoices/build/app.js", "build": "jsc"},
    {"type": "js", "url": "invoices/app/router.js", "buildTo": "invoices/build/app.js", "build": "jsc"}
];
